version: '3.8'
services:
  front-end:
    image: nutchayaporn/devtool-front:1.0.0
    build: ./front-end
    ports:
      - "3000:80"

  back-end:
    image: nutchayaporn/devtool-back:1.0.0
    build: ./back-test/app
    ports:
      - "5000:3000"